const jdmCars = [
    "Nissan Skyline GT-R R32",
    "Nissan Skyline GT-R R33",
    "Nissan 180SX",
    "Nissan Silvia S13",
    "Nissan Silvia S14",
    "Nissan Silvia S15",
    "Nissan 300ZX Z32",
    "Nissan Pulsar GTI-R",
    "Nissan Fairlady Z S30",
    "Nissan Laurel C33",
    "Toyota Supra MK3 (A70)",
    "Toyota Supra MK4 (A80)",
    "Toyota MR2 SW20",
    "Toyota MR2 AW11",
    "Toyota Chaser JZX90",
    "Toyota Chaser JZX100",
    "Toyota Cresta JZX90",
    "Toyota Mark II JZX90",
    "Toyota Soarer JZZ30",
    "Toyota Celica GT-Four ST185",
    "Toyota Celica GT-Four ST205",
    "Mazda RX-7 FC3S",
    "Mazda RX-7 FD3S",
    "Mazda MX-5 Miata NA",
    "Mazda MX-5 Miata NB",
    "Mazda Familia GT-X",
    "Mazda Lantis Type-R",
    "Honda NSX NA1",
    "Honda Integra Type R DC2",
    "Honda Prelude BB4",
    "Honda CR-X EF8",
    "Honda Civic SiR EG6",
    "Honda Civic SiR EK9",
    "Honda Accord SiR",
    "Mitsubishi Lancer Evolution I",
    "Mitsubishi Lancer Evolution II",
    "Mitsubishi Lancer Evolution III",
    "Mitsubishi Lancer Evolution IV",
    "Mitsubishi Galant VR-4",
    "Mitsubishi FTO GPX",
    "Mitsubishi GTO (3000GT)",
    "Subaru Impreza WRX GC8",
    "Subaru Legacy RS",
    "Suzuki Cappuccino",
    "Daihatsu Mira TR-XX Avanzato",
    "Autozam AZ-1",
    "Isuzu Gemini JT191",
    "Isuzu Piazza",
    "Nissan Bluebird SSS Attesa"
];

export function randomCar() {
    return jdmCars[Math.floor(Math.random() * jdmCars.length)]
}